import type { FixedMissionDefinition } from "../fixedMissionTypes";

export const FLOODED_MARKET_MISSION = Object.freeze({
  id: "flooded-market-01",
  label: "濁流の生活圏",
  destinationLabel: "浸水した郊外型スーパーマーケット",
  playerSpawn: { x: 0, y: 0.93, z: 4.8 },
  extractionPoint: { x: 0, y: 0.7, z: 4.8 },
  extractionRadius: 2.1,
  cart: {
    sourceId: "shopping-cart",
    label: "現地ショッピングカート",
    initialPosition: { x: 2.2, y: 0.48, z: -1.4 },
  },
  salvage: [
    {
      sourceId: "filter-01",
      label: "未開封の浄水フィルター 01",
      resourceType: "water-filter",
      carryMode: "hand",
      required: true,
      position: { x: -2.4, y: 0.32, z: 1.7 },
    },
    {
      sourceId: "filter-02",
      label: "未開封の浄水フィルター 02",
      resourceType: "water-filter",
      carryMode: "hand",
      required: true,
      position: { x: 0, y: 0.32, z: 0.6 },
    },
    {
      sourceId: "filter-03",
      label: "未開封の浄水フィルター 03",
      resourceType: "water-filter",
      carryMode: "hand",
      required: true,
      position: { x: 2.4, y: 0.32, z: 1.7 },
    },
    {
      sourceId: "cooling-coil",
      label: "密閉型冷却コイル",
      resourceType: "cooling-coil",
      carryMode: "cart-only",
      required: true,
      position: { x: 0, y: 0.38, z: -1.7 },
    },
  ],
  colliders: [
    { id: "market-floor", center: { x: 0, y: -0.25, z: 0 }, halfExtents: { x: 7, y: 0.25, z: 7 }, surface: "floor", visible: true },
    { id: "market-north-wall", center: { x: 0, y: 1.8, z: -7 }, halfExtents: { x: 7, y: 1.8, z: 0.25 }, surface: "wall", visible: true },
    { id: "market-south-port", center: { x: -4.5, y: 1.8, z: 7 }, halfExtents: { x: 2.5, y: 1.8, z: 0.25 }, surface: "wall", visible: true },
    { id: "market-south-starboard", center: { x: 4.5, y: 1.8, z: 7 }, halfExtents: { x: 2.5, y: 1.8, z: 0.25 }, surface: "wall", visible: true },
    { id: "market-west-wall", center: { x: -7, y: 1.8, z: 0 }, halfExtents: { x: 0.25, y: 1.8, z: 7 }, surface: "wall", visible: true },
    { id: "market-east-wall", center: { x: 7, y: 1.8, z: 0 }, halfExtents: { x: 0.25, y: 1.8, z: 7 }, surface: "wall", visible: true },
    { id: "shelf-west", center: { x: -4.6, y: 0.8, z: -1.2 }, halfExtents: { x: 0.55, y: 0.8, z: 2.8 }, surface: "fixture", visible: true },
    { id: "shelf-east", center: { x: 4.6, y: 0.8, z: -1.2 }, halfExtents: { x: 0.55, y: 0.8, z: 2.8 }, surface: "fixture", visible: true },
    { id: "cooling-shortcut-gate", center: { x: 0, y: 1, z: -2.65 }, halfExtents: { x: 1.05, y: 1, z: 0.12 }, surface: "fixture", visible: true },
  ],
  insertionAnchors: [
    { id: "south-center", position: { x: 0, y: 0.93, z: 4.8 }, cameraPosition: { x: 0, y: 3.2, z: 6.2 }, navigationNodeId: "extract", toolFreeExit: true },
    { id: "south-port", position: { x: -1.15, y: 0.93, z: 4.3 }, cameraPosition: { x: -1.4, y: 3.1, z: 6 }, navigationNodeId: "south-port", toolFreeExit: true },
    { id: "south-starboard", position: { x: 1.15, y: 0.93, z: 4.3 }, cameraPosition: { x: 1.4, y: 3.1, z: 6 }, navigationNodeId: "south-starboard", toolFreeExit: true },
    { id: "sales-port", position: { x: -2.4, y: 0.93, z: 1.2 }, cameraPosition: { x: -2.8, y: 3.2, z: 3.2 }, navigationNodeId: "sales-port", toolFreeExit: true },
    { id: "office", position: { x: -3.45, y: 0.93, z: -4.65 }, cameraPosition: { x: -3.1, y: 3.1, z: -2.7 }, navigationNodeId: "office", toolFreeExit: true },
    { id: "loading", position: { x: 3.45, y: 0.93, z: -4.65 }, cameraPosition: { x: 3.1, y: 3.1, z: -2.7 }, navigationNodeId: "loading", toolFreeExit: true },
  ],
  insertionPresets: [
    { id: "stable-solo", mode: "stable", anchorIds: ["south-center"] },
    { id: "stable-pair", mode: "stable", anchorIds: ["south-port", "south-starboard"] },
    { id: "stable-south", mode: "stable", anchorIds: ["south-center", "south-port", "south-starboard"] },
    { id: "paired-solo", mode: "paired", anchorIds: ["south-center"] },
    { id: "paired-duo", mode: "paired", anchorIds: ["south-center", "south-port"] },
    { id: "paired-sales", mode: "paired", anchorIds: ["south-center", "south-port", "sales-port"] },
    { id: "scattered-solo", mode: "scattered", anchorIds: ["south-center"] },
    { id: "scattered-duo", mode: "scattered", anchorIds: ["south-center", "office"] },
    { id: "scattered-facilities", mode: "scattered", anchorIds: ["south-center", "office", "loading"] },
  ],
  navigation: {
    nodes: [
      { id: "extract", position: { x: 0, y: 0.93, z: 4.8 } },
      { id: "south-port", position: { x: -1.15, y: 0.93, z: 4.3 } },
      { id: "south-starboard", position: { x: 1.15, y: 0.93, z: 4.3 } },
      { id: "sales-port", position: { x: -2.4, y: 0.93, z: 1.2 } },
      { id: "sales-center", position: { x: 0, y: 0.93, z: 1.1 } },
      { id: "sales-starboard", position: { x: 2.4, y: 0.93, z: 1.2 } },
      { id: "west-corridor", position: { x: -3.4, y: 0.93, z: -1.5 } },
      { id: "center-corridor", position: { x: 0, y: 0.93, z: -1.5 } },
      { id: "east-corridor", position: { x: 3.4, y: 0.93, z: -1.5 } },
      { id: "office", position: { x: -3.45, y: 0.93, z: -4.65 } },
      { id: "cooling", position: { x: 0, y: 0.93, z: -4.25 } },
      { id: "loading", position: { x: 3.45, y: 0.93, z: -4.65 } },
      { id: "underground", position: { x: 0, y: 0.93, z: -6.15 } },
    ],
    edges: [
      { id: "extract-port", from: "extract", to: "south-port", bidirectional: true, enabledByDefault: true },
      { id: "extract-starboard", from: "extract", to: "south-starboard", bidirectional: true, enabledByDefault: true },
      { id: "port-sales", from: "south-port", to: "sales-port", bidirectional: true, enabledByDefault: true },
      { id: "starboard-sales", from: "south-starboard", to: "sales-starboard", bidirectional: true, enabledByDefault: true },
      { id: "sales-port-center", from: "sales-port", to: "sales-center", bidirectional: true, enabledByDefault: true },
      { id: "sales-center-starboard", from: "sales-center", to: "sales-starboard", bidirectional: true, enabledByDefault: true },
      { id: "sales-west-corridor", from: "sales-port", to: "west-corridor", bidirectional: true, enabledByDefault: true },
      { id: "sales-east-corridor", from: "sales-starboard", to: "east-corridor", bidirectional: true, enabledByDefault: true },
      { id: "west-center", from: "west-corridor", to: "center-corridor", bidirectional: true, enabledByDefault: true },
      { id: "center-east", from: "center-corridor", to: "east-corridor", bidirectional: true, enabledByDefault: true },
      { id: "west-office", from: "west-corridor", to: "office", bidirectional: true, enabledByDefault: true },
      { id: "east-loading", from: "east-corridor", to: "loading", bidirectional: true, enabledByDefault: true },
      { id: "office-cooling", from: "office", to: "cooling", bidirectional: true, enabledByDefault: true },
      { id: "loading-cooling", from: "loading", to: "cooling", bidirectional: true, enabledByDefault: true },
      { id: "cooling-underground", from: "cooling", to: "underground", bidirectional: true, enabledByDefault: true },
      { id: "cooling-shortcut", from: "sales-center", to: "cooling", bidirectional: true, enabledByDefault: false },
    ],
  },
  signalZones: [
    { id: "parking", label: "駐車場", center: { x: 0, y: 0.9, z: 4.9 }, halfExtents: { x: 6.5, y: 3, z: 2 }, attenuation: 0.04 },
    { id: "sales", label: "売場", center: { x: 0, y: 0.9, z: 0.2 }, halfExtents: { x: 6.5, y: 3, z: 2.9 }, attenuation: 0.18 },
    { id: "cooling", label: "冷却設備室", center: { x: 0, y: 0.9, z: -4.2 }, halfExtents: { x: 2, y: 3, z: 1.5 }, attenuation: 0.44 },
    { id: "underground", label: "地下サービス通路", center: { x: 0, y: 0.9, z: -6.15 }, halfExtents: { x: 2.4, y: 3, z: 0.75 }, attenuation: 0.68 },
  ],
  searchZones: [
    { id: "parking", label: "駐車場", entrance: { x: 0, y: 0.93, z: 4.4 }, searchPoints: [{ x: -2.4, y: 0.93, z: 4.2 }, { x: 2.4, y: 0.93, z: 4.2 }], discoveries: [{ id: "parking-manifest", kind: "evidence", label: "濡れた搬入記録", position: { x: 2.4, y: 0.93, z: 4.2 } }] },
    { id: "sales", label: "売場", entrance: { x: 0, y: 0.93, z: 1.1 }, searchPoints: [{ x: -2.4, y: 0.93, z: 1.2 }, { x: 0, y: 0.93, z: 0.2 }, { x: 2.4, y: 0.93, z: 1.2 }], discoveries: [{ id: "sales-filter-cache", kind: "resource", label: "交換用フィルター箱", position: { x: 0, y: 0.93, z: 0.2 } }] },
    { id: "office", label: "管理事務室", entrance: { x: -3.45, y: 0.93, z: -4.1 }, searchPoints: [{ x: -3.45, y: 0.93, z: -4.65 }, { x: -2.8, y: 0.93, z: -5.1 }], discoveries: [{ id: "office-record", kind: "evidence", label: "非常電源ログ", position: { x: -2.8, y: 0.93, z: -5.1 } }] },
    { id: "loading", label: "搬入口", entrance: { x: 3.45, y: 0.93, z: -4.1 }, searchPoints: [{ x: 3.45, y: 0.93, z: -4.65 }, { x: 2.8, y: 0.93, z: -5.1 }], discoveries: [{ id: "loading-pallet", kind: "resource", label: "密封補修材", position: { x: 2.8, y: 0.93, z: -5.1 } }] },
    { id: "cooling", label: "冷却設備室", entrance: { x: 0, y: 0.93, z: -3.7 }, searchPoints: [{ x: -0.8, y: 0.93, z: -4.25 }, { x: 0.8, y: 0.93, z: -4.25 }], discoveries: [{ id: "cooling-diagnostic", kind: "evidence", label: "冷却系診断票", position: { x: 0.8, y: 0.93, z: -4.25 } }] },
    { id: "underground", label: "地下サービス通路", entrance: { x: 0, y: 0.93, z: -5.55 }, searchPoints: [{ x: -0.8, y: 0.93, z: -6.15 }, { x: 0.8, y: 0.93, z: -6.15 }], discoveries: [{ id: "underground-signal", kind: "evidence", label: "旧式中継器の残響", position: { x: 0.8, y: 0.93, z: -6.15 } }] },
  ],
  toolShortcuts: [
    { id: "cooling-gate", label: "冷却設備室の短縮ゲート", requiredDefinitionIds: ["crowbar", "bolt-cutter"], interactionPosition: { x: 0, y: 0.93, z: -2.1 }, colliderId: "cooling-shortcut-gate", navigationEdgeId: "cooling-shortcut" },
  ],
} satisfies FixedMissionDefinition);
